import type { NextConfig } from 'next'

/**
 * agentblog.dev.
 *
 * This file is also the reference output of `agentblog init`. Whatever the CLI
 * patches into a consumer's `next.config.ts` should end up looking like this, so
 * changes here and changes to `packages/cli/src/patchers/next-config.ts` belong
 * in the same commit.
 *
 * One setting below is agentblog.dev's own and is NOT written by the CLI:
 * `redirects`, which forwards the documentation to its own site. A consumer's
 * blog has none.
 */
const nextConfig: NextConfig = {
  /**
   * Bots listed here receive fully blocking metadata: `<title>` and every
   * `<meta>` tag land inside `<head>` rather than streaming into `<body>`.
   *
   * This value REPLACES the Next.js default list rather than extending it, so it
   * is the Next.js defaults union the AI crawlers. Narrowing it to only the AI
   * crawlers would silently drop Googlebot, Bingbot, and every social preview
   * bot, which trades an AI-search win for an SEO loss.
   *
   * Generated by `agentblog doctor --fix`. Run that command again after editing
   * rather than hand-editing, so the union stays intact.
   */
  htmlLimitedBots:
    /[\w-]+-Google|Google-[\w-]+|Chrome-Lighthouse|Slurp|DuckDuckBot|baiduspider|yandex|sogou|bitlybot|tumblr|vkShare|quora link preview|redditbot|ia_archiver|Bingbot|BingPreview|applebot|facebookexternalhit|facebookcatalog|Twitterbot|LinkedInBot|Slackbot|Discordbot|WhatsApp|SkypeUriPreview|Yeti|googleweblight|GPTBot|OAI-SearchBot|ChatGPT-User|OAI-AdsBot|ClaudeBot|Claude-SearchBot|Claude-User|anthropic-ai|PerplexityBot|Perplexity-User|Meta-ExternalAgent|Meta-ExternalFetcher|CCBot|Bytespider|Amazonbot|MistralAI-User|cohere-ai|DuckAssistBot|Diffbot|YouBot|Applebot-Extended/i,

  images: {
    // Next.js 16 rejects any quality not listed here with a 400 from the image
    // optimizer, and the default is [75]. The blog uses 75 for cards and 90 for
    // hero images.
    qualities: [75, 90],
    remotePatterns: [],
  },

  // The registry source is authored as if it were already in a consumer's
  // project, so it lives outside the usual app directories and needs to be
  // linted and type checked alongside them.
  outputFileTracingIncludes: {
    '/blog/**': ['./registry/blog/content/**/*'],
  },

  /*
   * NOT part of the `agentblog init` patch. The documentation moved to
   * docs.agentblog.dev, which is `apps/docs` in this repository.
   *
   * Every page that ever existed under `/docs` is mapped to its new URL
   * individually rather than through one catch-all, because the structure
   * changed at the same time as the host: a blanket redirect to the docs home
   * would turn every inbound link to a specific page into a bounce, and lose
   * whatever ranking that page had earned.
   *
   * `permanent: true` emits a 308, which search engines treat as a permanent
   * move and follow while passing the signals along.
   */
  async redirects() {
    const DOCS = 'https://docs.agentblog.dev'

    const moved: Record<string, string> = {
      introduction: '/',
      installation: '/installation',
      upgrading: '/guides/take-an-update',
      configuration: '/reference/configuration',
      'cli-reference': '/reference/cli',
      'blog-block': '/reference/files',
      'content-sources': '/reference/content-sources',
      theming: '/guides/match-your-design',
      'agent-layer': '/guides/write-with-your-agent',
      'geo-playbook': '/concepts/geo-playbook',
      'seo-geo-checklist': '/guides/pre-publish-checklist',
      troubleshooting: '/troubleshooting',
      'troubleshooting-cdn': '/troubleshooting/cdn-blocking-crawlers',
      monorepo: '/guides/monorepo',
      'ai-referrers': '/guides/measure-ai-traffic',
      'no-llms-txt': '/concepts/why-no-llms-txt',
      roadmap: '/project/roadmap',
      licensing: '/project/licensing',
      'llms.txt': '/llms.txt',
      'llms-full.txt': '/llms-full.txt',
    }

    return [
      ...Object.entries(moved).map(([from, to]) => ({
        source: `/docs/${from}`,
        destination: `${DOCS}${to}`,
        permanent: true,
      })),
      // The Markdown variants, which were `/docs/<slug>.md` and are now served
      // from the same path on the docs site.
      ...Object.entries(moved)
        .filter(([from]) => !from.endsWith('.txt'))
        .map(([from, to]) => ({
          source: `/docs/${from}.md`,
          destination: `${DOCS}${to === '/' ? '/index' : to}.md`,
          permanent: true,
        })),
      { source: '/docs', destination: DOCS, permanent: true },
      // Anything under `/docs` that is not named above. Last, so the specific
      // rules above win.
      { source: '/docs/:path*', destination: DOCS, permanent: true },
    ]
  },
}

export default nextConfig
