import type { NextConfig } from 'next'

/**
 * agentblog.dev.
 *
 * This file is also the reference output of `agentblog init`. Whatever the CLI
 * patches into a consumer's `next.config.ts` should end up looking like this, so
 * changes here and changes to `packages/cli/src/patchers/next-config.ts` belong
 * in the same commit.
 *
 * Two settings below are agentblog.dev's own and are NOT written by the CLI:
 * `rewrites` (the Markdown variants of the docs pages) and the `/docs/**` entry
 * in `outputFileTracingIncludes`. A consumer's blog has neither.
 */
const nextConfig: NextConfig = {
  /**
   * Bots listed here receive fully blocking metadata: `<title>` and every
   * `<meta>` tag land inside `<head>` rather than streaming into `<body>`.
   *
   * This value REPLACES the Next.js default list rather than extending it, so it
   * is the Next.js defaults union the AI crawlers. Narrowing it to only the AI
   * crawlers would silently drop Googlebot, Bingbot, and every social preview
   * bot, which trades an AI-search win for an SEO loss.
   *
   * Generated by `agentblog doctor --fix`. Run that command again after editing
   * rather than hand-editing, so the union stays intact.
   */
  htmlLimitedBots:
    /[\w-]+-Google|Google-[\w-]+|Chrome-Lighthouse|Slurp|DuckDuckBot|baiduspider|yandex|sogou|bitlybot|tumblr|vkShare|quora link preview|redditbot|ia_archiver|Bingbot|BingPreview|applebot|facebookexternalhit|facebookcatalog|Twitterbot|LinkedInBot|Slackbot|Discordbot|WhatsApp|SkypeUriPreview|Yeti|googleweblight|GPTBot|OAI-SearchBot|ChatGPT-User|OAI-AdsBot|ClaudeBot|Claude-SearchBot|Claude-User|anthropic-ai|PerplexityBot|Perplexity-User|Meta-ExternalAgent|Meta-ExternalFetcher|CCBot|Bytespider|Amazonbot|MistralAI-User|cohere-ai|DuckAssistBot|Diffbot|YouBot|Applebot-Extended/i,

  images: {
    // Next.js 16 rejects any quality not listed here with a 400 from the image
    // optimizer, and the default is [75]. The blog uses 75 for cards and 90 for
    // hero images.
    qualities: [75, 90],
    remotePatterns: [],
  },

  // The registry source is authored as if it were already in a consumer's
  // project, so it lives outside the usual app directories and needs to be
  // linted and type checked alongside them.
  outputFileTracingIncludes: {
    '/blog/**': ['./registry/blog/content/**/*'],
    '/docs/**': ['./content/docs/**/*'],
    '/docs-md/**': ['./content/docs/**/*'],
  },

  /*
   * NOT part of the `agentblog init` patch. This is agentblog.dev serving a
   * Markdown variant of every docs page, matching what Next.js does for its own
   * documentation.
   *
   * App Router segments are path segments rather than filename patterns, so
   * `/docs/installation.md` cannot be expressed as a route, and a page and a
   * route handler cannot share a segment folder. Rewriting to a sibling tree is
   * the way to get the URL we want.
   *
   * `:slug` is lazy in `path-to-regexp`, so it stops before the literal `.md`
   * rather than swallowing it.
   *
   * See `app/docs-md/[slug]/route.ts`.
   */
  async rewrites() {
    return [
      { source: '/docs/:slug.md', destination: '/docs-md/:slug' },
      { source: '/docs.md', destination: '/docs-md' },
    ]
  },
}

export default nextConfig
