/**
 * The `<script type="application/ld+json">` tag. One line of rendering, and two
 * decisions that are worth reading before you change either of them.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS IS A SERVER COMPONENT, AND MUST STAY ONE
 * ---------------------------------------------------------------------------
 * There is no `'use client'` at the top of this file and adding one breaks the
 * product rather than the build.
 *
 * AI crawlers do not execute JavaScript. GPTBot, ClaudeBot, and PerplexityBot
 * read the raw HTML the server returns and nothing else. Structured data
 * injected by a client component exists only in the rendered DOM, so a
 * DOM-based validator would pass it and every crawler this block exists to reach
 * would see a page with no schema at all. That is the worst class of failure
 * here: silent, invisible to the type checker, and invisible to the tools people
 * check with.
 *
 * `lib/schema.ts` imports `@/lib/config`, which is `server-only`, so the module
 * graph enforces this too. The comment is here because the error message that
 * enforcement produces will not explain why.
 *
 * ---------------------------------------------------------------------------
 * WHY `dangerouslySetInnerHTML` IS THE RIGHT CALL HERE
 * ---------------------------------------------------------------------------
 * React escapes text children as HTML entities, so `{json}` as a child would
 * write `&quot;` into the script body and produce JSON that no consumer can
 * parse. Setting the tag's inner HTML directly is the documented Next.js pattern
 * for JSON-LD and the only one that emits valid output.
 *
 * It is safe because of where the string comes from, not because of what it
 * contains. Every byte is machine-generated by `renderJsonLd`, which serializes
 * with `JSON.stringify` and then replaces `<` with its JSON unicode escape. That
 * replacement is what stops a post title containing a closing script tag from
 * ending the element early and turning the remaining JSON into markup. It
 * happens at exactly one point in the codebase so it can be reviewed once and
 * cannot be forgotten at a call site.
 *
 * The rule that follows: never pass this component a string built anywhere else,
 * and never serialize a schema object outside `renderJsonLd`.
 *
 * @see https://docs.agentblog.dev/reference/files
 */
import type { GraphNode } from '@/lib/schema'
import { renderJsonLd } from '@/lib/schema'

export interface JsonLdProps {
  /** The nodes for this page, from the builders in `lib/schema.ts`. */
  readonly nodes: readonly GraphNode[]
}

export function JsonLd({ nodes }: JsonLdProps) {
  // An empty `@graph` is markup that says nothing. Emit no tag rather than an
  // empty one, so a page that genuinely has no schema is obvious in view-source.
  if (nodes.length === 0) return null

  return (
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: renderJsonLd(nodes) }} />
  )
}

/** Alias so a route can import this either way. Same component. */
export default JsonLd
