/**
 * The `components.json` patcher: registering the `@agentblog` namespace.
 *
 * ===========================================================================
 * WHY `init` WRITES THIS INSTEAD OF ASKING THE USER TO
 * ===========================================================================
 * `shadcn add @agentblog/blog` resolves the `@agentblog` prefix through the
 * `registries` map in `components.json`. On a project that has never heard of
 * us, that map has no entry, so the headline command in the README failed with:
 *
 *     Unknown registry "@agentblog". Make sure it is defined under
 *     "registries" in your components.json
 *     You can also try a previous version to see if that works:
 *     npx shadcn@4.15.0 add ...
 *
 * The second half of that is a red herring: no version of shadcn resolves a
 * namespace that is not declared. So the one prerequisite `init` did not check
 * was the one that made "one command" false on the documented path.
 *
 * It is our namespace, pointing at our registry, added because the user asked
 * for our blog, and it goes through the same patch set as everything else: it
 * is printed as a diff, backed up, and removed by `agentblog revert`. Refusing
 * with the JSON to paste was the alternative and it is strictly worse: it turns
 * one command into two, for a line the user has no way to get wrong and no
 * reason to want to write.
 *
 * The output is written with `JSON.stringify(..., 2)`, which reformats the
 * file. `components.json` is generated by `shadcn init` and is already two
 * space JSON, so in practice the diff is the one added key.
 *
 * @see BUILD-SPEC section 12, the AgentBlog docs
 */
import type { PatchResult } from './next-config.ts'

/** Where the published registry lives. `{name}` is shadcn's own placeholder. */
export const DEFAULT_REGISTRY_URL = 'https://agentblog.dev/r/{name}.json'

export const AGENTBLOG_NAMESPACE = '@agentblog'

export function patchComponentsJson(source: string, registryUrl: string): PatchResult {
  const changes: string[] = []
  const declined: string[] = []

  let parsed: unknown
  try {
    parsed = JSON.parse(source)
  } catch (error) {
    return {
      source,
      changes,
      declined: [
        `components.json is not valid JSON (${error instanceof Error ? error.message : String(error)}), so the ${AGENTBLOG_NAMESPACE} registry was not added. Add "registries": { "${AGENTBLOG_NAMESPACE}": "${registryUrl}" } by hand.`,
      ],
    }
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return {
      source,
      changes,
      declined: [
        `components.json is not a JSON object, so the ${AGENTBLOG_NAMESPACE} registry was not added.`,
      ],
    }
  }

  const config = parsed as Record<string, unknown>
  const registries = config['registries']

  if (registries !== undefined && (typeof registries !== 'object' || registries === null)) {
    return {
      source,
      changes,
      declined: [
        `components.json has a "registries" key that is not an object, so it was left alone. Add "${AGENTBLOG_NAMESPACE}": "${registryUrl}" to it by hand.`,
      ],
    }
  }

  const map = { ...((registries as Record<string, unknown> | undefined) ?? {}) }
  const existing = map[AGENTBLOG_NAMESPACE]

  /*
   * An entry the user already has is never replaced. A private mirror, an
   * authenticated `{ url, headers }` object, or a local server during
   * development are all deliberate, and overwriting one to point at the public
   * registry would silently redirect every install away from where the user
   * meant it to go.
   */
  if (existing !== undefined) {
    const same = typeof existing === 'string' && existing === registryUrl
    if (!same) {
      declined.push(
        `components.json already maps ${AGENTBLOG_NAMESPACE} to ${JSON.stringify(existing)}. Left alone.`,
      )
    }
    return { source, changes, declined }
  }

  map[AGENTBLOG_NAMESPACE] = registryUrl
  config['registries'] = map
  changes.push(`components.json: registered ${AGENTBLOG_NAMESPACE} at ${registryUrl}`)

  return { source: `${JSON.stringify(config, null, 2)}\n`, changes, declined }
}
